keycloak_user: {
  shape: sql_table
  keycloak_user_id: string
  email: string
  email_verified: boolean
  enabled: boolean
  realm_id: string
  created_at: string
  identity_providers: array
}
product: {
  shape: sql_table
  product_id: string
  name: string
  price: number
  sku: string
  available_on: string
  retired_on: string
}
workspace: {
  shape: sql_table
  workspace_id: string
  workspace_name: string
  created_at: string
}
workspace_member: {
  shape: sql_table
  workspace_id: string
  keycloak_user_id: string
  role: string
  inserted_at: string
  removed_at: string
}
workspace.workspace_id -> workspace_member.workspace_id
workspace_member.keycloak_user_id -> keycloak_user.keycloak_user_id
workspace_member.workspace_id -> workspace.workspace_id
